apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/{{ .Values.mysql.database }}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: {{ .Values.mysql.usernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: {{ .Values.mysql.rootPasswordKey }}
            - name: DATALAKE_S3_BUCKET
              value: "{{ .Values.datalake.bucket }}"
            - name: AWS_REGION
              value: "{{ .Values.datalake.region }}"      




#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: bankapp
#spec:
#  replicas: {{ .Values.replicaCount }}
#  selector:
#    matchLabels:
#      app: bankapp
#  template:
#    metadata:
#      labels:
#        app: bankapp
#    spec:
#      containers:
#        - name: bankapp
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#          ports:
#            - containerPort: 8080
#          env:
#            - name: SPRING_DATASOURCE_URL
#              value: jdbc:mysql://mysql-service:3306/{{ .Values.mysql.database }}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#            - name: SPRING_DATASOURCE_USERNAME
#              value: root
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: {{ .Values.mysql.rootPassword | quote }}
